### ISSUE TITLE
Autodoc is not working on functions

### ISSUE THREAD

**Issue by eblur** [eblur/pyxsis#25]
I just noticed that the ReadTheDocs pages aren't showing the autodoc results for my library functions. For example: https://pyxsis.readthedocs.io/en/latest/plotting.html

Need to de-bug / test the autodoc tool for function docstrings.

**Comment by eblur** [comment]
And I can't reproduce this error locally on my machine, so it likely has something to do with my ReadTheDocs configuration I guess.

**Comment by eblur** [comment]
I had to add a command to the .readthedocs.yaml file to use "setuptools", which runs the setup.py script in the home directory.

 ``` 
python:
   version: 3.7
   install:
   - requirements: docs/requirements.txt
   - method: setuptools
     path: .
```
